---
title: "cancer-gene-plot"
author: "Taylan Kabbani"
date: "May 7, 2018"
output: html_document
---
```{r}
library(tidyverse)
library(ggpubr)
sample <- all_cancer_labeled[ ,1:20]
data <- all_cancer_labeled %>%
  gather("sample", "value", -gene) %>% 
  mutate(value = log(value)) %>% 
   spread(gene, value) %>%
  separate(sample, c("patient", "case", "stage1", "stage2", "stage"), sep = "_") %>% 
  separate(patient, c("unknown", "cancer")) %>% 
  select(-unknown, -case,-stage1,-stage2) %>% 
   mutate(stage = ifelse(stage > 1, 1, stage)) 

```

```{r}
all <- data %>% 
  group_by(cancer, stage) %>% 
  summarise(num = n()) %>% 
  spread(stage,num) %>% 
  
  rename(Normal = "0", Tumor = "1") %>% 
   mutate(Total = Normal + Tumor)
all
  
```


```{r}
target <- c("BRCA", "LUAD", "LUSC", "KIRC")
BRCA <- data %>% 
  filter(cancer %in% target) %>% 
   mutate(stage= ifelse(stage == 0, "Normal", stage)) %>% 
  mutate(stage= ifelse(stage == 1, "Tumor", stage)) 


theme_set(theme_pubr())
 plot_1 <-  ggplot(BRCA, aes(cancer, `ENSG00000196616-125`, col = stage, fill =stage))+
  geom_boxplot()+
    geom_jitter(shape=16, position=position_jitter(0.4))+
     scale_y_continuous(breaks = seq(0, 175, 50),limits=c(-5, 10))+ 
    scale_fill_discrete(name = "Case")+
    scale_color_discrete(name = "Case")
    
 plot_2 <- ggplot(BRCA, aes(cancer, `ENSG00000153002-1360`, col = stage, fill =stage))+
    geom_boxplot()+
    geom_jitter(shape=16, position=position_jitter(0.4))+
     scale_y_continuous(breaks = seq(0, 175, 50),limits=c(-5, 10))+ 
    scale_fill_discrete(name = "Case")+
    scale_color_discrete(name = "Case")
 
  plot_3 <- ggplot(BRCA, aes(cancer, `ENSG00000181092-9370`, col = stage, fill =stage))+
    geom_boxplot()+
    geom_jitter(shape=16, position=position_jitter(0.4))+
     scale_y_continuous(breaks = seq(0, 175, 50),limits=c(-5, 10))+ 
    scale_fill_discrete(name = "Case")+
    scale_color_discrete(name = "Case")
  
   plot_4 <- ggplot(BRCA, aes(cancer, `ENSG00000110484-4250`, col = stage, fill =stage))+
    geom_boxplot()+
    geom_jitter(shape=16, position=position_jitter(0.4))+
     scale_y_continuous(breaks = seq(0, 175, 50),limits=c(-5, 10))+ 
    scale_fill_discrete(name = "Case")+
    scale_color_discrete(name = "Case")
    
 figure <- ggarrange(plot_1, plot_2, plot_3,plot_4,
                    ncol = 2, nrow = 2)
figure
  
 
 


```

