---
title: "MLP"
author: "Taylan Kabbani"
date: "5/21/2018"
output: html_document
---

```{r}
# run once
library(tidyverse)
library(keras)
brca <- readRDS("brca_tidy_wide.rds")
selected_genes <- readRDS("selected_genes_pca.rds")
test_samples <- readRDS("test.rds")
train_samples <- readRDS("train.rds")
```

# Preparing input data

Refer to `crosscheck.Rmd` file for how B.Darendeli selected 784 genes (saved as `selected_genes_rmse.rds`). Refer to `.Rmd` file for how Hussam Al-Qabbani selected genes.

```{r}
no_of_samples <- nrow(train_samples) 

d_train <- brca %>% 
  semi_join(selected_genes) %>% 
  gather(sample, value, -gene) %>%
  semi_join(train_samples) %>% 
  mutate(value =ifelse(value < 1, 1, value)) %>% 
  #separate(sample, c("patient", "case", "stage"), sep="_") %>% 
  mutate(log_value = log(value)) %>% 
  select(-value) %>% 
  spread(sample, log_value) %>%          
  select(-gene) %>%
  as.matrix(byrow = TRUE) %>% 
  { colnames(.) ->> train_sample_names      # ugly hack to save intermediate https://stackoverflow.com/a/47879695/4579196
    dim(.) <- c(28,28,no_of_samples)  # changing dimensions of matrix and printing again
    .                                 # so that pipe is not broken: https://stackoverflow.com/a/44052271/4579196
  } %>% 
  aperm(c(3,1,2))

```

```{r}
dim(d_train)  # should be no_of_samples, 28 , 28
# d[1,1:28,1:28] should print data for first patient
```

```{r}
input <- array_reshape(d_train, c(no_of_samples, 28, 28, 1))
```

```{r}
labels <- train_sample_names %>% 
  as_data_frame() %>% 
  filter(value !="gene") %>% 
  # Normal=0, Tumor or Metastatic=1
  mutate(label= ifelse(grepl("Normal",value), 0, 1))  %T>%  # tee-operator
  { count(., label) %>% print() }  %>%   # count values - an ugly hack
  pull(label) %>% 
  array()
```

```{r}
dim(labels)
```

```{r}
batch_size <- 128
num_classes <- 2
epochs <- 30

x_train <- input
y_train <- labels

# The data, shuffled and split between train and test sets
#c(c(x_train, y_train), c(x_test, y_test)) %<-% 

x_train <- array_reshape(x_train, c(nrow(x_train), 784))
#x_test <- array_reshape(x_test, c(nrow(x_test), 784))

# Transform RGB values into [0,1] range
x_train <- x_train / 255
#x_test <- x_test / 255

cat(nrow(x_train), 'train samples\n')
#cat(nrow(x_test), 'test samples\n')

# Convert class vectors to binary class matrices
y_train <- to_categorical(y_train, num_classes)
#y_test <- to_categorical(y_test, num_classes)

# Define Model --------------------------------------------------------------

model <- keras_model_sequential()
model %>% 
  layer_dense(units = 1024, activation = 'relu', input_shape = c(784)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 512, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>% 
  layer_dense(units = 2, activation = 'softmax')

```

```{r}


model %>% compile(
  loss = 'categorical_crossentropy',
  optimizer = optimizer_rmsprop(),
  metrics = c('accuracy'))
```

```{r}
# Training & Evaluation 
# Fit model to data
history <- model %>% fit(
  x_train, y_train,
  batch_size = batch_size,
  epochs = epochs,
  verbose = 1,
  validation_split = 0.2)

```

```{r}
no_of_test_samples <- nrow(test_samples) 

d_test <- brca %>% 
  semi_join(selected_genes) %>% 
  gather(sample, value, -gene) %>%
  semi_join(test_samples) %>% 
  mutate(value =ifelse(value < 1, 1, value)) %>% 
  #separate(sample, c("patient", "case", "stage"), sep="_") %>% 
  mutate(log_value = log(value)) %>% 
  select(-value) %>% 
  spread(sample, log_value) %>%          
  select(-gene) %>%
  as.matrix(byrow = TRUE) %>% 
  { colnames(.) ->> test_sample_names      # ugly hack to save intermediate https://stackoverflow.com/a/47879695/4579196
    dim(.) <- c(28,28,no_of_test_samples)  # changing dimensions of matrix and printing again
    .                                 # so that pipe is not broken: https://stackoverflow.com/a/44052271/4579196
  } %>% 
  aperm(c(3,1,2))

input_test <- array_reshape(d_test, c(no_of_test_samples, 28, 28, 1))

input_test <- array_reshape(input_test, c(nrow(d_test), 784))
```

```{r}
labels_test <- test_sample_names %>% 
  as_data_frame() %>% 
  filter(value !="gene") %>% 
  # Normal=0, Tumor or Metastatic=1
  mutate(label= ifelse(grepl("Normal",value), 0, 1))  %T>%  # tee-operator
  { count(., label) %>% print() }  %>%   # count values - an ugly hack
  pull(label) %>% 
  array()
labels_test <- to_categorical(labels_test, num_classes)

```

```{r}
scores <- model %>% evaluate(
  input_test, labels_test, verbose = 1)

# Output metrics
cat('Test loss:', scores[[1]], '\n')
cat('Test accuracy:', scores[[2]], '\n')
```

```{r}
plot(history
  )
```

